apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance
spec:
  replicas: 5
  selector:
    matchLabels:
      app: insurance
  template:
    metadata:
      labels:
        app: insurance
    spec:
      containers:
      - name: insurance
        image: yomeshbarod/insurance:1
        ports:
        - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: insurance
spec:
  selector:
    app: insurance
  type: NodePort
  ports:
    - port: 80
      targetPort: 8082
      nodePort: 30007
